/**
 * Unit Tests: User Controller
 * Generated by: Unit Test Generator Agent
 * Bug fix: API-404 — type mismatch in getUserById (parseInt fix)
 * Framework: Jest
 *
 * Tests cover only functions changed or affected by the fix:
 *   - getUserById (changed: line 19 modified)
 *   - getAllUsers (related: same controller)
 *
 * FIRST compliant: Fast (mock req/res), Independent (per-test factories),
 * Repeatable (no external deps), Self-Validating (expect assertions),
 * Timely (covers changed code + regression test for the bug)
 */

const { getUserById, getAllUsers } = require('../src/controllers/userController');

// Helper factories — each test creates its own instances (Independent)
const mockReq = (params = {}) => ({ params });
const mockRes = () => {
  const res = {};
  res.json = jest.fn().mockReturnValue(res);
  res.status = jest.fn().mockReturnValue(res);
  return res;
};

describe('getUserById', () => {
  test('returns user for valid ID 123', async () => {
    const req = mockReq({ id: '123' });
    const res = mockRes();
    await getUserById(req, res);
    expect(res.json).toHaveBeenCalledWith({
      id: 123,
      name: 'Alice Smith',
      email: 'alice@example.com'
    });
  });

  test('returns user for valid ID 456', async () => {
    const req = mockReq({ id: '456' });
    const res = mockRes();
    await getUserById(req, res);
    expect(res.json).toHaveBeenCalledWith({
      id: 456,
      name: 'Bob Johnson',
      email: 'bob@example.com'
    });
  });

  test('returns user for valid ID 789', async () => {
    const req = mockReq({ id: '789' });
    const res = mockRes();
    await getUserById(req, res);
    expect(res.json).toHaveBeenCalledWith({
      id: 789,
      name: 'Charlie Brown',
      email: 'charlie@example.com'
    });
  });

  test('returns 404 for non-existent ID 999', async () => {
    const req = mockReq({ id: '999' });
    const res = mockRes();
    await getUserById(req, res);
    expect(res.status).toHaveBeenCalledWith(404);
    expect(res.json).toHaveBeenCalledWith({ error: 'User not found' });
  });

  test('returns 404 for non-numeric ID "abc"', async () => {
    const req = mockReq({ id: 'abc' });
    const res = mockRes();
    await getUserById(req, res);
    expect(res.status).toHaveBeenCalledWith(404);
    expect(res.json).toHaveBeenCalledWith({ error: 'User not found' });
  });

  test('[REGRESSION] string "123" resolves to user (API-404 fix)', async () => {
    // This test specifically validates the bug fix.
    // Before the fix: req.params.id = "123" (string) was compared with === to 123 (number),
    // which always returned false, causing a 404 for every valid user.
    // After the fix: parseInt("123", 10) = 123 (number), comparison succeeds.
    const req = mockReq({ id: '123' }); // Express always passes strings for URL params
    const res = mockRes();
    await getUserById(req, res);
    expect(res.json).toHaveBeenCalledWith(
      expect.objectContaining({ id: 123, name: 'Alice Smith' })
    );
    expect(res.status).not.toHaveBeenCalled();
  });
});

describe('getAllUsers', () => {
  test('returns all 3 users', async () => {
    const req = mockReq();
    const res = mockRes();
    await getAllUsers(req, res);
    const returnedUsers = res.json.mock.calls[0][0];
    expect(returnedUsers).toHaveLength(3);
  });

  test('each user has id, name, and email', async () => {
    const req = mockReq();
    const res = mockRes();
    await getAllUsers(req, res);
    const returnedUsers = res.json.mock.calls[0][0];
    returnedUsers.forEach(user => {
      expect(user).toHaveProperty('id');
      expect(user).toHaveProperty('name');
      expect(user).toHaveProperty('email');
    });
  });
});
